[package]
name = "coldsonic"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-compat = "0.2.6"
bytes = "1.9"
directories = "6.0"
iced = { version = "0.14.0", features = ["smol", "image"] }
iced_fonts = { version = "0.3", features = ["lucide"] }
itertools = "0.15.0"
opensubsonic = "0.4.0"
reqwest = "0.13.5"
serde = { version = "1.0.229", features = ["derive"] }
smol = "2.0.2"
thiserror = "2.0.20"
toml = "0.8"
